### PR TITLE
Set FQDN to include vagrantup.com again for non-windows operating sys…

### PR DESCRIPTION
**Pull request by spion06**
…tems

### CODE REVIEW

**Comment by cheeseplus** [comment]
What problem is this solving? I'm happy to review just want to make sure this is solving an issue.

**Comment by spion06** [comment]
This is fixing a regression that was introduced when windows support was added. Before this the node fqdn was `instance.name`.vagrantup.com. now the fqdn is just `instance.name`. I use this sometimes to detect that my cookbook is running inside of an integration test and flex a few values automatically. Also, it's generally a good idea to have a domain name so ohai attributes like `node['fqdn']` and `node['domain']` are set. Also so commands like `hostname -f` and `hostname -d` work. The workaround for me now is to just lock into the version of kitchen-vagrant that doesn't have windows support.

**Comment by cheeseplus** [comment]
:+1:

**Comment by mwrock** [comment]
My only concern is that it has been well over a year since introducing the above mentioned change and adding the domain name could possibly brake someone expecting the current convention. We do have other ways to detect if the chef run is running from TK.

**Pull request merged**
