### PR TITLE
Translate CPU count for VMWare

### PR DESCRIPTION
**Pull request by whiteley**
Only fair to support both options commonly (and in the documentation) configured together.

### CODE REVIEW

**Comment by tyler-ball** [comment]
Can you add 2 tests similar to https://github.com/test-kitchen/kitchen-vagrant/blob/master/spec/kitchen/driver/vagrant_spec.rb#L1162-L1187 ?  After that, we should be able to accept this.

If we start getting more branching logic in this ERB to support VMWare, we'll need to reapproach how we populate the Vagrantfile.

**Comment by whiteley** [comment]
Sorry I skipped the tests the first time and understandable about this getting messier. I think with more customizations, it's quite reasonable to use your own `vagrantfile_erb` but these two options seem often configured together. Thanks!

**Comment by fnichol** [comment]
That's great, thank you!

**Comment by fnichol** [comment]
Shipped out in 0.17.0.beta.4, thanks all!

**Pull request merged**
