### PR TITLE
Fix generated Vagrantfile type issues

### LINKED ISSUE #236: Generated Vagrantfile has type issues
I'm using latest vagrant, test-kitchen, virtualbox. Nothing helps me to bring machine up:
```yaml
---
driver:
  name: vagrant
  ssh:
    insert_key: false
  customize:
    cpus: 1
    memory: 1024
```
Produces:
```ruby
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-6.7"
  c.vm.hostname = "default-centos-67"
  c.ssh.insert_key = "false"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--cpus", "1"]
    p.customize ["modifyvm", :id, "--memory", "1024"]
  end
end
```

Here is false as string ```"false"```

Relates to #130

### PR DESCRIPTION
**Pull request by OBrienCommaJosh**
Adds boolean value support to ssh config option

Fixes #236
Credit: @jsirex - [Original Fix](https://github.com/test-kitchen/kitchen-vagrant/issues/236#issuecomment-234486655)

### CODE REVIEW

**Comment by OBrienCommaJosh** [comment]
Trying to narrow down where I busted the tests. Looks like possibly [here](https://github.com/test-kitchen/kitchen-vagrant/blob/master/spec/kitchen/driver/vagrant_spec.rb#L313-L317)?

@cheeseplus @mwrock Will you let me know if I'm on track here? Will try to get the tests updated over the next few days if so.

**Comment by mwrock** [comment]
oh its not you at all. I just merged a PR that should fix tests. Just rebase your pr onto that and it should turn green.

**Comment by mwrock** [comment]
👍

**Comment by OBrienCommaJosh** [comment]
🤘 Rockin'! Looks like we're in business.

**Comment by cheeseplus** [comment]
+1

**Pull request merged**
