### PR TITLE
support multi-machine Vagrantfile

### PR DESCRIPTION
**Pull request by robmbrooks**
I am using an existing multi-machine Vagrantfile and this allows it to work with kitchen-vagrant.

### CODE REVIEW

**Comment by coderanger** [comment]
Or more concretely: use of the various "raw Vagrantfile" features is very much an at-your-own-risk kind of trapdoor that exists to allow for unforeseen solutions, not tacit acknowledgement that we support that full surface area of Vagrant :)

**Comment by robmbrooks** [comment]
Understood! :) It reduces my risks by not having to manage two Vagrantfiles, one for dev, one for test-kitchen.

In kitchen-vagrant we change "vagrant up" to "vagrant up instance.platform.name" if config[:multi_machine] is true (defaults to false).

**Comment by coderanger** [comment]
That's not an unreasonable thing to do, but is out of scope for this plugin. You would have to create your own if you wanted to support that (though it could subclass this one).

**Comment by robmbrooks** [comment]
the given pull request achieves this, I'm already doing it with a locally compiled gem. Is there any good reason to subclass to add 8 lines?

**Comment by coderanger** [comment]
Many, but that discussion is complex and nuanced so it's up to you to decide what is best. Going to close this out.

**Comment by robmbrooks** [comment]
that's fine, I assume those that need it will pull from here

**Pull request closed without merging**
