### PR TITLE
Add support for ovirt4 vagrant provider

### PR DESCRIPTION
**Pull request by myoung34**

### CODE REVIEW

**Comment by coderanger** [comment]
@cheeseplus What do you think about just making that section an `else` catch-all?

**Comment by cheeseplus** [comment]
Probably be good to make that an an `else` that way we don't need to add something each time. If a different formatting is needed then we can case it. @myoung34

**Comment by myoung34** [comment]
I'm OK with all that, I just needed to be able to use the template. Want me to refactor this one?

**Comment by cheeseplus** [comment]
If you could make it an else which would still pass the tests that'd be great @myoung34 and we can get this one in and released.

**Comment by myoung34** [comment]
Resolved by #290

**Pull request closed without merging**
