### PR TITLE
Support `createhd`, `storageattach` option for Virtualbox

### PR DESCRIPTION
**Pull request by w1mvy**
Update Vagrantfile template.

support Virtualbox options `createhd` and `storageattach`
- https://www.virtualbox.org/manual/ch08.html#vboxmanage-createvdi
- https://www.virtualbox.org/manual/ch08.html#vboxmanage-storageattach

like this

``` markdown
platforms:
  - name: ubuntu-14.04
    driver:
      box: trusty64
      customize:
        memory: 1024
        cpus: 4
        nictype1: virtio
        createhd:
          filename: ./tmp/diskfile1.vmdk
          size: 100 * 1024
        storageattach:
          storagectl: IDE Controller
          port: 1
          device: 0
          type: hdd
          medium: ./tmp/diskfile1.vmdk
```

### CODE REVIEW

**Comment by cheeseplus** [comment]
Happy to merge this but would love to have tests for this first.

**Comment by lgeinert** [comment]
If you are going to do createhd and storageattach does it make sense to do modifyhd?   Reason being, we cannot create a shareable disk initially, we have to do it as a second step.  
>      vb.customize ['createhd', '--filename', "../#{disk_name}.vdi", '--size', (size * 1024).floor, '--variant', 'fixed']
     vb.customize ['modifyhd', "../#{disk_name}.vdi", '--type', 'shareable']

**Comment by timhaintz** [comment]
Is this still progressing? Would like to be able to mount an ISO. Would like to be able to help, not sure how though.

https://www.virtualbox.org/manual/ch08.html#vboxmanage-storagectl
https://www.virtualbox.org/manual/ch08.html#vboxmanage-storageattach

Like: 
VBoxManage.exe storagectl "<uuid|vmname>" --name IDE --add ide
VBoxManage.exe storageattach "<uuid|vmname>" --storagectl IDE --port 0 --device 0 --type dvddrive --medium "X:\Folder\containing\the.iso"

Or as below in .kitchen.yml
---
driver:
  name: vagrant
  provision:
  customize:
    memory: 2048
    cpus: 2
    storagectl:
       name: "IDE_2_4_ISO"
       add: ide
     storageattach:
       storagectl: "IDE_2_4_ISO"
       port: 1
       device: 1
       type: dvddrive
       medium: D:\My.iso
Thanks, Tim.

**Comment by shortdudey123** [comment]
This was merged under https://github.com/test-kitchen/kitchen-vagrant/pull/246
So this PR can be closed

**Pull request closed without merging**
