### PR TITLE
Add support for managed-servers Vagrant provider

### PR DESCRIPTION
**Pull request by kbruner**
This simple addition to the Vagrantfile template is enough to add support for the managed-servers Vagrant provider (https://github.com/tknerr/vagrant-managed-servers).  This will basically allow test-kitchen to be used as a 'push' service for already-provisioned servers.  (We have some development/test cases where this may be required.)

Sample .kitchen.yml:

```
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: false

platforms:
  - name: managed_server
    driver:
      provider: managed
      box: 'managed-server-dummy'
      box_url: 'https://github.com/tknerr/vagrant-managed-servers/raw/master/dummy.box'
      ssh_key: '/path/to/ssh/key'
      username: 'root'
      customize:
        server: '10.0.0.123'

...
```

### CODE REVIEW

**Comment by tknerr** [comment]
Oh, nice @kbruner :+1: 

Looks good to me.

**Comment by tknerr** [comment]
Once we have Vagrant 1.6 compatibility (see #125) we could also use `box: "tknerr/managed-server-dummy"` instead of the rather long `box_url`

**Comment by tknerr** [comment]
@kbruner on a second thought, I'm honestly wondering how you reset your managed servers to a pristine state before running the tests? :-)

**Comment by kbruner** [comment]
Yes, this is not an ideal test situation.  It is a corner case for one team here who got a speshul snowflake setup awhile ago.  Right now their test systems is managed by a production chef server, except for their app recipes, which they push via littlechef.  Adding this support in vagrant would at least get them more aligned with our test-kitchen development standards.  We'll need infrastructure changes in our Chef environment to be able to get them 100% on the chef servers for their permanent environments, though.

**Comment by fnichol** [comment]
Hello @kbruner, looks good! As master now (finally) has test coverage, I took the liberty of rebasing this against master and adding a couple of specs in 8f197651302d801e433ee3b3675800c97e2ca273. Thank you!

**Pull request closed without merging**
